#!/usr/bin/env python3
import os
import re
import glob
import xml.etree.ElementTree as ET

TAGS_FILE = "src/tags_plugin_name.hpp"
KCFG_DIR = "src/contents/kcfg"
OUTPUT_FILE = "src/contents/docs/database/plugins_properties.md"

def get_tags():
    ids = []
    if not os.path.exists(TAGS_FILE):
        print(f"Error: {TAGS_FILE} not found.")
        return ids

    regex = re.compile(r'CREATE_PROPERTY\s*\(\s*QString\s*,\s*\w+\s*,\s*QStringLiteral\s*\(\s*"([^"]+)"\s*\)\s*\)')

    with open(TAGS_FILE, 'r') as f:
        for line in f:
            match = regex.search(line)
            if match:
                ids.append(match.group(1))
    return sorted(ids)

def main():
    if not os.path.exists(KCFG_DIR):
        print(f"Error: Directory '{KCFG_DIR}' not found. Run this from the repo source root.")
        exit(1)

    tags = get_tags()

    lines = [
        "<!--",
        "  AUTOGENERATED FILE - DO NOT MODIFY MANUALLY.",
        "  This file is generated by: util/generate_command_docs.py",
        "-->",
        "",
        "# Plugin Properties",
        "",
        "The following properties can be modified or queried via the [local server](../user_interface/local_server.md).",
        "",
        "| Plugin ID | Property | Type | Default |",
        "| :--- | :--- | :--- | :--- |"
    ]

    found_plugins = 0

    for tag in tags:
        kcfg_path = os.path.join(KCFG_DIR, f"easyeffects_db_{tag}.kcfg")

        if not os.path.exists(kcfg_path):
            continue

        try:
            tree = ET.parse(kcfg_path)
            root = tree.getroot()
            ns = {"kcfg": "http://www.kde.org/standards/kcfg/1.0"}

            esc = lambda s: str(s).replace("|", r"\|") if s else ""

            for group in root.findall("kcfg:group", ns):
                for entry in group.findall("kcfg:entry", ns):
                    prop_name = entry.get('name')
                    prop_type = entry.get('type')

                    default_node = entry.find("kcfg:default", ns)
                    default_val = "-"

                    if default_node is not None:
                        if default_node.get("code") == "true":
                            default_val = "*calculated*"
                        elif default_node.text:
                            default_val = default_node.text

                    choices_html = ""
                    if prop_type == "Enum":
                        choices = entry.find("kcfg:choices", ns)
                        if choices is not None:
                            names = [c.get("name") for c in choices.findall("kcfg:choice", ns)]
                            choices_html = f" <br><small>({', '.join(names)})</small>"

                    row = f"| **{esc(tag)}** | `{esc(prop_name)}` | {esc(prop_type)}{choices_html} | `{esc(default_val)}` |"
                    lines.append(row)

            found_plugins += 1
        except Exception as e:
            print(f"Error parsing {kcfg_path}: {e}")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")

    print(f"Documentation generated at: {OUTPUT_FILE} for {found_plugins} plugins.")

if __name__ == "__main__":
    main()
