.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Boyuan Yang <byang@debian.org>
.\"
.TH pulseeffects 1 "2019-03-19"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pulseeffects \- Audio effects for PulseAudio applications
.SH SYNOPSIS
.B pulseeffects
.RI [ options ] ...
.br
This manual page documents briefly the
.B pulseeffects
commands.
.PP
\fBpulseeffects\fP is a graphical program that tweaks the audio effects
system-wide or for individual PulseAudio applications.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, invoke the program with \-\-help option.
.TP
.B \-h, \-\-help
Show summary of options.
.SH SEE ALSO
The detailed documentation can be found on upstream Wiki page:
.br
.BR https://github.com/wwmm/pulseeffects/wiki
